# Automatically generated by configure - do not modify
SRC_PATH=/home/nivek/Workspace/qcow2-snapshots/qemu-4.2-base/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
